# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"\xa2\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.task.TaskResult.Status\x12\x18\n\x10result_data_json\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"-\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\t\n\x05RETRY\x10\x02\",\n\x07TaskAck\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\x42\n\x0bTaskService\x12\x33\n\x0cReportResult\x12\x10.task.TaskResult\x1a\r.task.TaskAck(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKRESULT']._serialized_start=21
  _globals['_TASKRESULT']._serialized_end=183
  _globals['_TASKRESULT_STATUS']._serialized_start=138
  _globals['_TASKRESULT_STATUS']._serialized_end=183
  _globals['_TASKACK']._serialized_start=185
  _globals['_TASKACK']._serialized_end=229
  _globals['_TASKSERVICE']._serialized_start=231
  _globals['_TASKSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
