[project]
name = "python-async-and-performance"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp",
    "asyncpg",
    "fastapi",
    "faiss-cpu",
    "httpx",
    "langchain",
    "langchain-community",
    "langchain-core",
    "langgraph",
    "numpy",
    "openai",
    "psutil",
    "pydantic",
    "pydantic-settings",
    "pytest",
    "redis",
    "requests",
    "sqlalchemy",
    "starlette",
    "uvicorn",
]
