[project]
name = "week05-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"python-dotenv",
	"duckduckgo-search>=8.1.1",
	"fastmcp[cli]>=2.12.3",
	"langchain>=0.3.7",
	"langchain-community>=0.3.5",
	"langchain-mcp-adapters>=0.1.6",
	"langgraph>=0.2.46",
	"dashscope>=1.24.6",
]
